### ISSUE TITLE
How ccdHeightMMPerPixel is calculated

### ISSUE THREAD

**Issue by kubbo** [Theta-Limited/DroneModels#5]
I am very happy to see your excellent open source project, but I have a question about the camera parameters.
How are ccdWidthMMPerPixel and ccdHeightMMPerPixel calculated? Taking djiZENMUSEH20 as an example, I found that the CMOS size of the camera on the official website is 1/1.7''. Isn’t the corresponding width and height 7.6 and 5.7? Why are 7.53 and 5.64 here? Looking forward to your reply

**Comment by mkrupczak3** [comment]
Hi @kubbo,

Trying to determine the actual CMOS size of each camera model is a huge headache, and requires some confusing leaps of logic.

In the camera industry, the advertised figure (e.g. 1/1.7") is expressed in an arbitrary notation called [optical format](https://en.wikipedia.org/wiki/Optical_format), which comes from very long ago when video tube cameras only had about 2/3'rds of their surface as usable space. Even this 2/3'rds figure is at best an estimate, and varies for every manufacturer and camera model. Basically, think of the advertised sensor size as a marketing gimmick, with little relation to reality.

I've found the best resources for estimating true sensor sizes to be the following links:

https://www.digicamdb.com/sensor-sizes/
https://commonlands.com/blogs/technical/cmos-sensor-size
https://www.djzphoto.com/blog/2018/12/5/dji-drone-quick-specs-amp-comparison-page

Ultimately though, without access to the actual camera itself, all we can do is make good estimates and see if they produce good results. Camera calibration, either using [our script](https://github.com/Theta-Limited/camera-calibration) or software like PIX4D, provides a more precise measured figure.

**Comment by mkrupczak3** [comment]
For some of the sensors, such as most of the Sony CMOS and the FLIR uncooled microbolometer thermal sensors, we obtain the physical pixel size directly from the manufacturer's published technical spec sheet

**Comment by mkrupczak3** [comment]
Closing this issue for now, I think this is too complicated to discuss in the README.md for this repo.

If you still have questions, please reach out at support@theta.limited

**Comment by kubbo** [comment]
Thank you very much for your reply
